Controllers/OperationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System;
using RestaurMap.Models;

namespace RestaurMap.Controllers;

public class OperationsController : Controller
{
    private UserManager<ApplicationUser> userManager;
    private RoleManager<ApplicationRole> roleManager;

    public OperationsController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
    {
        this.userManager = userManager;
        this.roleManager = roleManager;
    }

    public ViewResult Create() => View();

    [HttpPost]
    public async Task<IActionResult> Create(User user)
    {
        if (ModelState.IsValid)
        {
            ApplicationUser appUser = new ApplicationUser
            {
                UserName = user.Name,
                Email = user.Email
            };

            IdentityResult result = await userManager.CreateAsync(appUser, user.Password);

            if (result.Succeeded)
            {

                await userManager.AddToRoleAsync(appUser, "User");

                ViewBag.Message = "User Created Successfully";
            }
            else
            {
                foreach (IdentityError error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
        }
        return View(user);
    }
    public IActionResult CreateRole() => View();

    [HttpPost]
    public async Task<IActionResult> CreateRole([Required] string name)
    {
        if (ModelState.IsValid)
        {
            IdentityResult result = await roleManager.CreateAsync(new ApplicationRole() { Name = name });
            if (result.Succeeded)
                ViewBag.Message = "Role Created Successfully";
            else
            {
                foreach (IdentityError error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
        }
        return View();
    }
}

Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurMap.Models;
using RestaurMap.Services;
using System.Data;
using System.Security.Cryptography;
using System.Threading;

namespace RestaurMap.Controllers;

[Authorize(Roles = "Admin")]
public class RestaurantController : Controller
{
    private readonly IRestaurantsService _restaurantService;
    public RestaurantController(IRestaurantsService restaurantsService)
    {
        _restaurantService = restaurantsService;   
    }
    // GET: RestaurantController
    public async Task<ActionResult> Index(CancellationToken cancellationToken)
    {
        List<Restaurant> restaurants = new List<Restaurant>();
        restaurants = await _restaurantService.GetAllAsync(cancellationToken);
        return View(restaurants);
    }
    // GET: RestaurantController/Details/5
    public ActionResult Details(int id)
    {
        return View();
    }

    // GET: RestaurantController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: RestaurantController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(Restaurant restaurant)
    {
        await _restaurantService.CreateAsync(restaurant);
        return RedirectToAction("Index");
    }
    // POST: RestaurantController/Edit/5
    [HttpGet]
    public async Task<IActionResult> Edit()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(string id, Restaurant restaurant)
    {
        await _restaurantService.EditOneAsync(id, restaurant);
        return RedirectToAction("Index");
    }
    // GET: RestaurantController/Delete/5
    [HttpGet]
    public async Task<IActionResult> Delete(string id, CancellationToken cancellationToken)
    {
        var toRemove = await _restaurantService.GetOneAsync(id, cancellationToken);
        return View(toRemove);
    }

    // POST: RestaurantController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(Restaurant restaurant, CancellationToken cancellationToken)
    {
        await _restaurantService.RemoveAsync(restaurant.Id ,cancellationToken);
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurMap</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/leaflet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/leaflet-easy-button.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/leaflet-tag-filter-button.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/leaflet-search.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/leaflet-coordinates.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.css">

    <script src="~/js/leaflet.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.js"></script>
    <script src="~/js/leaflet-easy-button.js"></script>
    <script src="~/js/leaflet-coordinates.js"></script>
    <script src="~/js/leaflet-tag-filter-button.js"></script>
    <script src="~/js/leaflet-search.js"></script>
    <link rel="stylesheet" href="~/RestaurMap.styles.css" asp-append-version="true" />
    <style>
        .easy-button-button {
          display: block !important;
        }

        .tag-filter-tags-container {
          left: 30px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurMap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @{
                            if (User.IsInRole("Admin"))

                            {
                                <li class="nav-item">
                                    <a asp-controller="Restaurant" asp-action="Index" class="nav-link text-dark">Admin Panel</a>
                                </li>
                            }
                        }
                        @{
                            if (!User?.Identity?.IsAuthenticated ?? false)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Operations" asp-action="Create">Register</a>
                                </li>
                            }
                        }
                        @{
                            if (User?.Identity?.IsAuthenticated ?? false)
                            {
                                <li class="nav-item">
                                    <u>Welcome: @User.Identity.Name</u>
                                    <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                                </li>
                            }
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RestaurMap - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/map.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>